dependencies {
    implementation 'io.projectreactor:reactor-core:3.4.10'

    compileOnly("studio.lunarlabs.universe:universe-shared:0.0.1")
    compileOnly("studio.lunarlabs.universe:universe-spigot:0.0.1")

    compileOnly "io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT"

    compileOnly "redis.clients:jedis:5.1.2"
    compileOnly "org.mongodb:mongodb-driver-reactivestreams:5.0.0"
}